Feature/add mvvmlight
FortechRomania/SportsPlanner pull request #11
Opened 2017-03-23 16:34 UTC by mariusbob

Added MVVM-Light to and made it work throughout all the platforms.

2017-03-24 22:03 UTC, cosminstirbu requested changes

2017-03-24 22:03 UTC, cosminstirbu commented on SportsPlanner.Droid/MainActivity.cs
> +            GetEventsBtn.SetCommand("Click", Vm.GetEventsCommand);
Is there any other approach that doesn't require hardcoded "magic" strings?

2017-03-24 22:03 UTC, cosminstirbu commented on SportsPlanner.Droid/MainActivity.cs
> +        public Button GetEventsBtn
We can probably move all the "find by views" in a partial class like in the video you sent on Slack.

2017-03-24 22:03 UTC, cosminstirbu commented on SportsPlanner.Droid/SportsPlanner.Droid.csproj.bak
> +﻿<?xml version="1.0" encoding="utf-8"?>
Not sure this needs to be committed

2017-03-24 22:03 UTC, cosminstirbu commented on SportsPlanner.Droid/SportsPlanner.Droid.csproj.user
> +﻿<?xml version="1.0" encoding="utf-8"?>
This seems like a file we would want to add to .gitignore

2017-03-24 22:03 UTC, cosminstirbu commented on SportsPlanner.Droid/App.cs
> +                    DispatcherHelper.Initialize();
It looks like we call this just on Android? Any specific reason why this is different from iOS ?

2017-03-24 22:03 UTC, cosminstirbu commented on SportsPlanner.iOS/SportsPlanner.iOS.csproj.user
>  <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
This seems like a file we would want to add to .gitignore

2017-03-24 22:03 UTC, cosminstirbu commented on SportsPlanner.iOS/ViewController.cs
> +            Button.SetCommand("TouchUpInside", Vm.GetEventsCommand);
Is there a way we can avoid these magic strings?

2017-03-24 22:03 UTC, cosminstirbu commented on SportsPlanner/ViewModels/MainViewModel.cs
> +        private IEventsGateway _iEventsGateway;
No need for the i in front of the variable name, same for the rest of the file.

2017-03-24 22:03 UTC, cosminstirbu commented on SportsPlanner/ViewModels/ViewModelLocator.cs
> +            SimpleIoc.Default.Register<IDialogService, DialogService>();
Does the DialogService as an iOS / Android and UWP implementation?
If so, that's pretty cool.

2017-03-27 12:34 UTC, mariusbob commented on SportsPlanner.Droid/App.cs
> +                    DispatcherHelper.Initialize();
i'm not sure 100% how it works, but it definitely should be used in iOS project too.

2017-03-27 12:35 UTC, mariusbob commented on SportsPlanner.Droid/MainActivity.cs
> +            GetEventsBtn.SetCommand("Click", Vm.GetEventsCommand);
Maybe we can avoid the hardcoded strings by `nameOf`
https://msdn.microsoft.com/en-us/library/dn986596.aspx

2017-03-27 12:36 UTC, mariusbob commented on SportsPlanner.iOS/SportsPlanner.iOS.csproj.user
>  <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
Maybe we can avoid the hardcoded strings by `nameOf`
https://msdn.microsoft.com/en-us/library/dn986596.aspx

2017-03-27 12:36 UTC, mariusbob commented on SportsPlanner.iOS/ViewController.cs
> +            Button.SetCommand("TouchUpInside", Vm.GetEventsCommand);
Maybe we can avoid the hardcoded strings by `nameOf`
https://msdn.microsoft.com/en-us/library/dn986596.aspx

2017-03-27 12:36 UTC, mariusbob commented on SportsPlanner/ViewModels/MainViewModel.cs
> +        private IEventsGateway _iEventsGateway;
you're right

2017-03-27 12:38 UTC, mariusbob commented on SportsPlanner/ViewModels/ViewModelLocator.cs
> +            SimpleIoc.Default.Register<IDialogService, DialogService>();
Actually, MVVM Light has different implementation for both, iOS and Android platforms. You don't have to take care about the platform, mvvm light does it for you.

2017-03-27 12:50 UTC, mariusbob commented on SportsPlanner.Droid/MainActivity.cs
> +        public Button GetEventsBtn
indeed.

2017-03-27 12:55 UTC, mariusbob commented on SportsPlanner.iOS/SportsPlanner.iOS.csproj.user
>  <Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
done

2017-03-27 18:18 UTC, mariusbob commented on SportsPlanner.Droid/SportsPlanner.Droid.csproj.bak
> +﻿<?xml version="1.0" encoding="utf-8"?>
added it to gitignore

2017-03-27 18:24 UTC, cosminstirbu approved these changes

2017-03-27 18:25 UTC, CatalinPrata requested changes

2017-03-27 18:25 UTC, CatalinPrata commented on SportsPlanner.iOS/AppDelegate.cs
> +            DispatcherHelper.Initialize(application);
Could you please format this method?

2017-03-27 18:25 UTC, CatalinPrata commented on SportsPlanner.iOS/ViewController.cs
> +        private MainViewModel Vm
What is Vm? :P maybe a better naming would be better.

2017-03-27 18:50 UTC, CatalinPrata approved these changes

2017-03-27 19:01 UTC, merged